version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    networks:
      - custom_newtork

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default
    depends_on:
      - frontend
      - backend
      - redis
    networks:
      - custom_newtork
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend_container
    links:
      - redis
    networks:
      - custom_newtork
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    restart: unless-stopped
    labels:
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - custom_newtork

networks:
  custom_newtork:
    driver: bridge
